from octopwn.clients.scannerbase import ScannerConsoleBase as ScannerConsoleBase

class ChatUtil(ScannerConsoleBase):
    def __init__(self, client_id, connection, cmd_q, msg_queue, prompt, octopwnobj) -> None: ...
    async def console_command_handler(self, cmd: str, h_username: str = None): ...
