from mdutils.mdutils import MdUtils
from octopwn.clients.scannerbase import ScannerConsoleBase as ScannerConsoleBase
from octopwn.common.credential import OCTOPWN_CREDENTIALS_TSV_HDR as OCTOPWN_CREDENTIALS_TSV_HDR
from octopwn.common.target import OCTOPWN_TARGETS_TSV_HDR as OCTOPWN_TARGETS_TSV_HDR
from octopwn.core import OctoPwn as OctoPwn
from octopwn.scanners import OCTOPWN_SCANNER_TABLE as OCTOPWN_SCANNER_TABLE

async def generate_report(octopwn: OctoPwn, fname: str = None, add_credential_secrets: bool = True): ...
async def report_credentials(octopwn: OctoPwn, mdFile: MdUtils, add_plaintext: bool = False): ...
async def report_targets(octopwn: OctoPwn, mdFile: MdUtils): ...
async def report_actions_on_targets(octopwn: OctoPwn, mdFile: MdUtils): ...
async def report_actions_on_target(octopwn: OctoPwn, mdFile: MdUtils, cid, config, client): ...
async def report_scanners(octopwn: OctoPwn, mdFile: MdUtils): ...
async def report_scanner_activity(octopwn: OctoPwn, mdFile: MdUtils, name, description, clientid, config, scanner: ScannerConsoleBase): ...
