from _typeshed import Incomplete

class FILETIME:
    dwLowDateTime: Incomplete
    dwHighDateTime: Incomplete
    datetime: Incomplete
    def __init__(self) -> None: ...
    @staticmethod
    def from_bytes(data): ...
    def calc_dt(self) -> None: ...
    @staticmethod
    def from_dict(d): ...
    @staticmethod
    def from_buffer(buff): ...
