from _typeshed import Incomplete
from octopwn.clients.scannerbase import ScannerConsoleBase as ScannerConsoleBase
from octopwn.common.clientconfig import UtilsConfig as UtilsConfig
from octopwn.servers.wsnetws.agent import WSNETWSAgent as WSNETWSAgent
from octopwn.servers.wsnetws.protocol import CMD as CMD

class IOTServer(ScannerConsoleBase):
    params: Incomplete
    wsserver: Incomplete
    devices: Incomplete
    def __init__(self, client_id, connection, cmd_q, msg_queue, prompt, octopwnobj) -> None: ...
    def get_device_id(self): ...
    async def handle_device(self, ws, path) -> None: ...
    async def stop(self) -> None: ...
    async def do_serve(self) -> None: ...
