import http.server
from _typeshed import Incomplete

class HttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    extensions_map: Incomplete
    zipfile: Incomplete
    def __init__(self, *args, zipfile: Incomplete | None = None, **kwargs) -> None: ...
    def end_headers(self) -> None: ...
    def translate_path(self, path): ...
    def do_GET(self) -> None: ...

def serve_zipfile(ip: str, port: int = 8000, ssl_ctx: Incomplete | None = None, zip_path: str = ''): ...
