from _typeshed import Incomplete
from octopwn.clients.scannerbase import ScannerConsoleBase as ScannerConsoleBase
from octopwn.servers.protocols.DNS import DNSAAAAResource as DNSAAAAResource, DNSAResource as DNSAResource, DNSType as DNSType
from octopwn.servers.protocols.LLMNR import LLMNRPacket as LLMNRPacket, LLMNRResponse as LLMNRResponse

class LLMNRServer(ScannerConsoleBase):
    params: Incomplete
    server_task: Incomplete
    def __init__(self, client_id, connection, cmd_q, msg_queue, prompt, octopwnobj) -> None: ...
    async def start(self): ...
    async def socketsetup(self): ...
    async def do_serve(self): ...
    async def do_spoof(self) -> None: ...
    async def do_spooftarget(self, target, ip: str = 'SELF') -> None: ...
    async def stop(self): ...
